# Autogenerated by nbdev

from __future__ import annotations

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lexios',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/lexios',
                'lib_path': 'lexios'},
  'syms': {'lexios.callback': {}, 'lexios.core': {'lexios.core.foo': ('matter.html#foo', 'lexios/core.py')}, 'lexios.matter': {}}}
