# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lexios',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/lexios',
                'lib_path': 'lexios'},
  'syms': {'lexios.core': {'lexios.core.foo': ('matter.html#foo', 'lexios/core.py')}}}
