# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_callback.ipynb.

# %% auto 0
from __future__ import annotations

__all__ = []

# %% ../nbs/07_callback.ipynb 5
_events = L.split('before_create_unv after_create_unv \
                  before_create_env after_create_env \
                  before_create_matter after_create_matter \
                  before_get_prop after_get_prop before_change_prop after_change_prop \
                  before_get_law after_get_law before_change_law after_change_law')
